### ISSUE TITLE
安卓 14 无法选择其他文件夹存储

### ISSUE THREAD

**Issue by lwlbeng** [1250422131/bilibilias#110]
同题

**Comment by 1250422131** [comment]
你应该是在使用Beta版本？这是由于项目更新了compilesdk和targetsdk到34，但我们并没有为API的升级做好适配，所以导致了这个问题，目前APP已经在计划重新设计APP的存储权限和路径选则方案，随后版本将修复这个错误问题，你可以先改用正式版本（2.0.31）或者等待2.0.4的正式发布。

**Comment by 1250422131** [comment]
该问题已经得到了良好的解决：

[2.0.3-YuHeng-Beta](https://github.com/1250422131/bilibilias/releases/tag/2.0.4-%E7%8E%89%E8%A1%A1-Beta)

请在这里下载新的测试版本检查。
