### ISSUE TITLE
无法解析番剧

### ISSUE THREAD

**Issue by Gu-ZT** [1250422131/bilibilias#3]
如题

**Comment by 1250422131** [comment]
是这样的，bilibilias是可以解析番剧的。下面我简单介绍方法。

1.请在bilibili打开一个番剧进行播放，在这个页面中，你可以看到缓存旁边的 ** _转发按钮_ ** ，点击它，选择 **更多**，在弹出的页面选择 **BILIBILIAS** ，这样B站会将分享内容传给APP， **BILIBILIAS会自动进行解析**  ，当然你需要注意的是，这不能是港台地区限制的番剧。

> 如果你仍然没有找到分享的办法，请前往 **https://docs.qq.com/doc/DVUxhb3FtbnhrYUNq?pub=1&dver=2.1.27053861** 这个是软件轮播图中 **bilibilias黑科技** 页面，这里第一条就写了如何使用分享解析。并且写了bilibilias历代更新的隐藏功能，你可以看到一些平时注意不到的功能，并且这个页面将保持更新。

2.另外使用 **BV/AV/SS/EP号或者对应链接** 在解析页面输入，当然大多数用户并不知道如何找番剧的bv编号因此你可以使用对应链接，如果是链接，那么仅仅可以输入番剧页面的链接，不能有其余文字出现，你可以在哔哩哔哩网页端找到番剧进行播放，复制播放页面的地址，这也是所有视频通用解析方法。如果输入的链接或者编号里有多余内容，将造成无法解析。

最后你如果还是没有解决，请联系我 **QQ:1250422131**

**Comment by 1250422131** [comment]
请问你根据我发的提示，问题得到解决了吗？
