### ISSUE TITLE
2.0.42严重闪退问题

### ISSUE THREAD

**Issue by YeiJ** [1250422131/bilibilias#345]
更新到该版本之后首次打开软件所有功能正常 用几分钟后闪退
再次打开搜索功能失效 输入内容点击搜索会立即闪退
通过账号历史记录等途径可正常下载视频 一两分钟后仍会闪退

设备信息 安卓14 骁龙8Gen2

**Comment by 1250422131** [comment]
非常抱歉，正在检查这个问题是因为CDN还是APP问题，你可以留意下这个问题。

**Comment by 1250422131** [comment]
经服务器同学检查，此次问题由CDN引起，导致请求发生重定向错误，目前正在调整策略。
