### ISSUE TITLE
闪退 澎湃os

### ISSUE THREAD

**Issue by KohanChi** [1250422131/bilibilias#383]
澎湃os闪退，清除缓存重新下载都没用。

**Comment by KohanChi** [comment]
版本为2.0.42和2.0.43（都闪退）

**Comment by KohanChi** [comment]
经实测，基本所有版本的BILIAS都闪退

**Comment by 1250422131** [comment]
嘿！我也是澎湃OS，目前看上去没有闪退，我猜测可能是CDN问题，交由运维同学检查这个问题 @zxy678

**Comment by 1250422131** [comment]
现在这个问题还存在吗？

**Comment by KohanChi** [comment]
现在这个问题还存在，并且有群友澎湃OS与我有同样的情况

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1250422131** [comment]
方便提供下你所在的网络环境吗？是哪个运营商，闪退日志也可以上传一下

**Comment by KohanChi** [comment]
io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class com.imcys.bilibilias.home.ui.model.OldUpdateDataBean' but was 'class io.ktor.utils.io.do'
In response from `https://api.misakamoe.com/app/bilibilias.php?type=json&version=3.9`
Response status `403 `
Response header `ContentType: text/html; charset=UTF-8`
Request header `Accept: application/json`

You can read how to resolve NoTransformationFoundException at FAQ:
https://ktor.io/docs/faq.html#no-transformation-found-exception
 at io.ktor.client.call.do.擅长捉弄的高木同学(SourceFile:243)
 at com.imcys.bilibilias.base.network.NetworkService$getUpdateData$2.invokeSuspend(SourceFile:85)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
 at kotlinx.coroutines.implements.run(SourceFile:125)
 at androidx.appcompat.widget.break.run(SourceFile:13)
 at ta.break.run(SourceFile:3)
 at ta.if.run(SourceFile:96)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: ***@***.***, Dispatchers.Main]



经本人实测与网络无关，之前使用同网络的情况下不会出现这种问题。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1250422131** [comment]
403响应，这看上去被拦截了

**Comment by KohanChi** [comment]
感谢你的提醒，在开启穿梭VPN回国之后不再闪退了。
谢谢！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 1250422131** [comment]
也感谢你的反馈，你本人目前在国外吗？还是使用了VPN代理？这对我们有很大的帮助！

**Comment by 1250422131** [comment]
再次感谢，祝你生活娱快！
