### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [1250422131/bilibilias#392]
请问可以发布到 F-Droid 吗？

**Comment by 1250422131** [comment]
当然可以的，不过请确保上传的apk是没有修改过的。

**Comment by linsui** [comment]
F-Droid 不是直接上传 apk 而是从源码构建。要想在 F-Droid 发布，要去掉 mtj-sdk 这种不开源的库。请问这样可以吗？

**Comment by 1250422131** [comment]
没有问题，但是统计功能是带在源代码当中的，如果你要这么做可能需要考虑单独建立分支，每次更新同步主分支删除统计相关内容，或者编写gradle脚本，确保构建时排除统计代码和相关库引用。

如果你遇到了一些问题，可以继续联系我帮助你。

**Comment by linsui** [comment]
我大致看了一下应该用脚本去掉就可以。如果有问题我再请教，感谢 :+1:

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15518

**Comment by linsui** [comment]
大概一周内会发布

**Comment by 1250422131** [comment]
以后对于项目的发版，F-Droid 会自己拉取代码编译发布吗？还是我们必须手动处理这个

**Comment by linsui** [comment]
只要提高 version code 然后打 tag 就行，F-Droid 会自动更新。

**Comment by linsui** [comment]
已经发布了，感谢帮助！

**Comment by 1250422131** [comment]
OK，如果后面还有其他需要可以继续系我

**Comment by 1250422131** [comment]
我还有一些疑问，就像前面提到的，要在f-droid发布就需要去除百度统计等一些统计库，但是后续的发布中可能也携带了这个库，尽管我已经在考虑迁移，但是这个库会在后面几个版本仍然存在，那么我发布新tag会遇到问题吗？

**Comment by 1250422131** [comment]
好的，我明白了，感谢！

**Comment by linsui** [comment]
https://github.com/1250422131/bilibilias/blob/b3600d6a59afdf808c31d85d23c2d7b23eb849e8/app/build.gradle.kts#L147C9-L147C13

这个 palay 是 typo 吧

**Comment by 1250422131** [comment]
> https://github.com/1250422131/bilibilias/blob/b3600d6a59afdf808c31d85d23c2d7b23eb849e8/app/build.gradle.kts#L147C9-L147C13
> 
> 这个 palay 是 typo 吧

是的，我修正一下

**Comment by linsui** [comment]
https://github.com/1250422131/bilibilias-ffmpeg/releases/tag/0.1.1 这个文件我们得重新构建，可以写个脚本放仓库里吗？

**Comment by 1250422131** [comment]
辛苦，我已经增加了这个依赖，它用于安卓10开始使用的沙箱存储。但我不是很理解，因为enabledAnalytics 关闭后的确不会引入Firebase 和 Google Play Core，为什么还需要再进行处理。
