### ISSUE TITLE
[BUG]工具页输入BV号弹出碧诗

### ISSUE THREAD

**Issue by TC999** [1250422131/bilibilias#442]
如图
![Screenshot_20240910_183704.jpg](https://github.com/user-attachments/assets/678b7f26-4633-42f7-b4ba-21291f34c3d4)
这个BV号是正常的

**Comment by 1250422131** [comment]
关于这个问题是由正则表达式引起的，目前我还在修复它，下个版本它应该会正常。

**Comment by 1250422131** [comment]
该问题已经修复
