### ISSUE TITLE
可以直接看吗？

### ISSUE THREAD

**Issue by oldsento** [1250422131/bilibilias#452]
或者后续会支持？

**Comment by SOCK-MAGIC** [comment]
?能说的详细一点吗？

**Comment by oldsento** [comment]
> ?能说的详细一点吗？

就是可以正常浏览和播放b站视频，还有搜索，

可以参考以下几乎都是来源的第三方b
1.搭理搭理
2.bilineo
3.Bilihub
4.pipepipe
5.biliyou
6.bilimiao
7.pilipala

**Comment by SOCK-MAGIC** [comment]
可以播放B站视频
