### ISSUE TITLE
线上崩溃

### ISSUE THREAD

**Issue by ChengYang1998** [1250422131/bilibilias#495]
作者大大，线上崩啦快看看，应该和我的 PR 没关系
日志看来好像是 JSON 数据中缺少 allowance_count 字段
![image](https://github.com/user-attachments/assets/89b65987-2c49-4efe-9c23-7e02ca452f87)

**Comment by 1250422131** [comment]
30号之前我可能都在外面，确实是没时间维护，这次的错误可能是b站接口删除了部分字段，如果可以的话辛苦你检查下问题。

**Comment by 1250422131** [comment]
该问题已经被 #499 修复，等待新版本发布
